name: 'Build, Pack, Push'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Add github source
      run: dotnet nuget add source https://nuget.pkg.github.com/modulery/index.json -n github -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }} --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore ./src/GithubNugetTest.DerivedPackage/GithubNugetTest.DerivedPackage.csproj

    - name: Build
      run: dotnet build ./src/GithubNugetTest.DerivedPackage/GithubNugetTest.DerivedPackage.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack ./src/GithubNugetTest.DerivedPackage/GithubNugetTest.DerivedPackage.csproj --configuration Release --no-build --output ./src/GithubNugetTest.DerivedPackage/bin/Release

    - name: NuGet Push
      run: dotnet nuget push ".\src\GithubNugetTest.DerivedPackage\bin\Release\*.nupkg" --source "https://nuget.pkg.github.com/modulery/index.json" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
      
    - name: Print folder contents
      if: ${{ failure() }}
      run: |
        ls -R .\src
        ls -R D:\a